//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class message : global::System.Configuration.ApplicationSettingsBase {
        
        private static message defaultInstance = ((message)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new message())));
        
        public static message Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("缺少对应图片！")]
        public string Message_NOTexture {
            get {
                return ((string)(this["Message_NOTexture"]));
            }
            set {
                this["Message_NOTexture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("缺少对应文件夹！")]
        public string Message_NOFile {
            get {
                return ((string)(this["Message_NOFile"]));
            }
            set {
                this["Message_NOFile"] = value;
            }
        }
    }
}
